language: go

env:
  global:
    - GO111MODULE=on
    - GOFLAGS=-mod=vendor

install: skip

jobs:
  include:
    - name: "project compiles"
      script:
        - "go build"
    - name: "gofmt"
      script:
        - 'if [[ "$(gofmt -l ./ | tee /tmp/hubtty-playground-gofmt | wc -l)" -gt 0 ]]; then { echo "Run gofmt on these files:" | cat - /tmp/hubtty-playground-gofmt; return 1; }; fi'
    - name: "unit tests"
      script:
        - "go test ./..."
